# Generated by Django 5.1.4 on 2026-05-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('content_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='projects.researchproject')),
            ],
            options={
                'verbose_name_plural': 'summaries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_number', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='resources.resource')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='summaries.summary')),
            ],
            options={
                'ordering': ['citation_number'],
                'unique_together': {('summary', 'citation_number')},
            },
        ),
    ]
