# Generated by Django 5.1.4 on 2026-05-10 11:38

import django.db.models.deletion
import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('file', 'PDF File'), ('url', 'URL Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=resources.models.resource_upload_path)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.researchproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
